version: '3.1'

services:
  app:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
      args:
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: db
    ports:
      - 5432:5432

volumes:
  postgres-data:
